# Generated by Django 4.2 on 2023-04-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='question_text',
            new_name='name',
        ),
    ]
