# Generated by Django 4.2 on 2023-04-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_question_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
