# Generated by Django 4.2 on 2023-04-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_question_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROCESS', 'In Process'), ('COMPLETED', 'Completed')], default='NEW', max_length=15),
        ),
    ]
