# Generated by Django 4.2 on 2023-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROCESS', 'In Process'), ('COMPLITED', 'Complited')], default='NEW', max_length=15),
        ),
    ]
